version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sh:/dbfiles/init-user-db.sh

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
    
  app:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - postgres

volumes:
  postgres-data:
